### ISSUE TITLE
Criar um tutorial na wiki para explicar como fazer legendas no youtube

### ISSUE THREAD

**Issue by dunossauro** [dunossauro/curso-python-selenium#1]
Minha ideia principal é abrir uma guia na wiki do projeto para que possamos montar um tutorial básico de como criar legendas para os vídeos no Youtube

**Comment by eduardosramos** [comment]
Há algumas ferramentas que podem ajudar:
1. Express Scribe;
2. Digitação por voz do Google docs (ajuda se tiver um VAC instalado e o áudio sendo direcionado para este dispositivo virtual) o recurso também é chamado de virtual audio output router. 
    2.1 https://vac.muzychenko.net/en/
    2.2 https://github.com/mattingalls/Soundflower/
3. Com as ferramentas instaladas (e.g, 2.1 ou 2.2) é só dar o play e apertar a tecla de função da digitação por voz. 
4. Revisão 1: 
    4.1 Áudio desacelerado para conferir palavra por palavra e remoção ou não de cacoetes (ou se vai deixar ipsis litteris);
    4.2 Revisão 2: Conferir a gramática.
Nesta fase é importante a revisão das regras de pontuação, palavras como mas, mais, por que? porque porquê e por quê, dentre inúmeras outras (por isso gostaria que chamasse um contato ou mais de Letras para a revisão full).
5. Legendagem.
Depois de realizada a transcrição, o importante é marcar o timecode e pode ser utilizado o app SubRip (https://github.com/Legisign/subrip). Essa parte que fazia era outra galera. Eu só entregava os textos prontos.

Por enquanto é isso.

**Comment by hemilioaraujo** [comment]
Fiz um PR para criar o diretório de legendas e estou fazendo um README no mesmo para explicar os passos para contribuir. 

@eduardosramos , se a PR for aceita, adiciona este conteúdo nos arquivos para ficar registrado com seu nome.

**Comment by GabrielSimonetto** [comment]
[00:10:14]
E sabe, tem sempre alguém pra tipo, terceirizar a sua decisão, e aí, a gente tem que começar falando sobre isso. E eu peguei um ponto específico pra gente discutir aqui, que é uma coisa que eu vivo ouvindo as pessoas dizendo, é um conceito que vem da psicologia, mas a galera quer botar isso em tudo que é “tech”. Né, então eu acho que a gente precisa falar sobre isso. Geralmente, parece um assunto marketeiro né, começar falando sobre isso, né? Hã, p.s. nada contra coaches, obrigado Hélio, também, nada contra, pode fazer o que quiser, não querendo me vender um curso… É, o Fabricio falou que essa é a palestra de sete faces 2.0, hã, essa é a palestra de sete faces 2.0, junto com a live antiga, então, junto com outro keynote que eu dei na PyCon Amazônia, então, a idéia é a gente juntar tudo aqui hoje e tentar sair do outro lado.

Hã… então é isso, o Amom mandou vintão ai pra nós, brigado Amom! Cara, saudade de ti velho. Então beleza: a gente vai começar. Vamos dividir aqui, vamos falar, então, na real o que que as pessoas vendem quando elas vão falar do mercado de tecnologia, tá, e de como é que as coisas deveriam funcionar, tal tal tal… 

A gente vai falar sobre “hard skills” no começo, né, porque as pessoas costumam falar, né “pô você devia investir em hard skills” e, falar tipo “ah você precisa saber várias linguagens, vários frameworks, você precisa aprender dialetos, precisa aprender programação funcional, design patterns, engenharia de software”, e a gente divide isso em hard skills. 

Hã… e aí quando a gente pega a gente vai falar sobre “soft skills”, que é o inverso disso, que são as habilidades… hã… que a gente vai usar como relativas ao comportamento que a gente tem, né. Eu coloquei aqui a relação do “eu”, né, o seu “eu” em relação àquilo que a gente faz e… Nossa, o Yros cara! Um beijo! Brigado por estar aqui. Então… em relação àquilo que a gente coloca da nossa vida em relação àquilo que a gente desenvolve né, então, por exemplo: ah, como a gente se comporta, como a gente conversa com as outras pessoas, e o que que a gente pode fazer pra essas coisas funcionarem bem. Então... a galera costuma falar que bons programadores precisam de hard skills e soft skills pra conseguir mixar esse conceito. É uma filosofia de “boteco” quando a gente vai parar pra pensar no mundo real isso aqui, porque a empresa só tá interessada em quem tem hard skills, e se você tá num lugar que não tem soft skills, cara, vá embora, tá ligado, que é a melhor coisa que você faz, arruma outro emprego, não sofre, não precisa.

Mas, tudo bem. A gente vai partir desse ponto, e desse ponto eu quero levar vocês, tipo, pra gente discutir a tecnologia de boteco aqui pra gente ir pra frente, eu quero trazer, hm, OpenBSD (risos) - “Aberto e  BomSão Demais!” É… as minhas siglas são muito ruins, os títulos dos slides não dão muito certo, mas eu (risos) “BomSão Demais” é meio complicado (risos), mas é isso.

Pô, algumas pessoas me mandaram tipo assim: “OpenBSD!? Por que vai falar de OpenBSD?”. Então eu acho que pra gente entender como é que as coisas funcionam e… por trás de toda a filosofia das coisas que me trás até aqui, essa pessoa que vos falo, e em frente a essa camera, que tô parecendo um maluco, porque to olhando pra uma camera.

Então… vamo lá, vamo viajar no tempo e tentar entender um dos projetos que eu acho que é um dos projetos mais bonitos que eu conheço. Hã… essa foto maravilhosa aqui, ela é do rack da galera da OpenBSD, do pessoal, todas as pessoas desenvolvidas que mantem essa coisa, eles tem esse rack, é uma foto do rack deles em 2009, e… é muito interessante, né, você ve que essa é toda a infraestrutura que a galera tinha em 2009, e é um projeto que já é antigo, né, o projeto do OpenBSD foi iniciado em 1994, tendo a primeira release “lançada” em 95 e eles ainda tão em atividade até hoje né, então, sei lá, mais de 20 anos desenvolvendo uma coisa, um grupo de pessoas que se juntou pra fazer isso.

Uma outra skill muito massa do OpenBSD, é que o OpenBSD é o sistema operacional mais seguro do mundo. Sério, “ah, mas meu windows serve”, “ah, mas meu kernel linux”, não, isso aqui a gente tá falando de segurança, pessoas que param, sentam, e olham, e tentam fazer o sistema mais seguro de todos os tempos.

[00:15:05]

**Comment by Isadoramenezes** [comment]
### Fluxo da transcrição #00:
1. Acessar o arquivo no docs: https://docs.google.com/document/d/1zB8ArO-1dDBxbpXe7JqQohPHN2YDhAroWEXta0idx4o/edit?usp=sharing
2. Marcar com comentários [início e fim] o trecho a ser transcrito por você [Estamos dividindo em trechos de cinco minutos, mas pode ser mais ou menos]
3. Fazer a revisão
4. Ao finalizar procurar a mensagem " LEGENDA CORRIGIDA " enviada por último e adicionar o trecho que você fez

---
Esse é o fluxo de hoje para essa transcrição, modificações serão comentadas aqui, caso alguém fora do grupo queira ajudar.
