### ISSUE TITLE
Aula 4b com erro

### ISSUE THREAD

**Issue by gustav0mirand4** [dunossauro/curso-python-selenium#15]
A aula 4b esta com erro de "Page Not Found" se eu der um get na url ```https://selenium.dunossauro.live/aula_4_b.html```.

**Comment by dunossauro** [comment]
@gustav0mirand4, acho que tu está acessando a url errada. A numeração das aulas começa com 0. 01, 02, 03, 04, ...

O link correto é https://selenium.dunossauro.live/aula_04_b.html
