### ISSUE TITLE
[Certificado] Eduardo Augusto Klosowski

### ISSUE THREAD

**Issue by eduardoklosowski** [dunossauro/curso-python-selenium#7]
Link do meu repositório: https://github.com/eduardoklosowski/exercicio-curso-selenium

**Comment by dunossauro** [comment]
Parabéns jovem. Ficou muito massa.

Curti de mais que fez até o reflection. Parabéns pelo código. Achei ANIMAL :heart:. Se postar em algum lugar, me marca que eu vou adorar ver <3 <3

![Certificado](https://user-images.githubusercontent.com/6801122/91121541-64ca6c00-e66e-11ea-99f5-fa1323b9c3bf.jpg)

O link em PDF: https://drive.google.com/drive/folders/1uP3tlTw8uR3P22MOjrazrENkcVXXvbIY?usp=sharing
